-- Sort keymaps (built-in :sort, aliased as :Sort)
vim.keymap.set('n', '<leader>so', ':Sort<CR>', { desc = 'Sort lines' })
vim.keymap.set('v', '<leader>so', "'<,'>Sort<CR>", { desc = 'Sort selection' })
vim.keymap.set('n', '<leader>si', ':Sort i<CR>', { desc = 'Sort lines (ignore case)' })
vim.keymap.set('v', '<leader>si', "'<,'>Sort i<CR>", { desc = 'Sort selection (ignore case)' })
vim.keymap.set('n', '<leader>su', ':Sort u<CR>', { desc = 'Sort lines (unique)' })
vim.keymap.set('v', '<leader>su', "'<,'>Sort u<CR>", { desc = 'Sort selection (unique)' })
vim.keymap.set('n', '<leader>sn', ':Sort n<CR>', { desc = 'Sort lines (numeric)' })
vim.keymap.set('v', '<leader>sn', "'<,'>Sort n<CR>", { desc = 'Sort selection (numeric)' })
