" Vim syntax file for plain text
" Language: Plain text
" Maintainer: Generated by Neovim config
" Last Change: 2026-04-13

if exists("b:current_syntax")
  finish
endif

" Simple plain text syntax - no highlighting
syntax clear

let b:current_syntax = "txt"