return {
    'folke/which-key.nvim',
    event = 'VeryLazy',
    enabled = true,
    opts = {
        preset = 'modern',
        expand = 0,
        spec = {
            {
                mode = { 'n', 'v' },
                { '<leader>?', '<cmd>Cheatsheet<cr>', desc = 'Cheatsheet' },
                { 'gr', group = 'LSP Functions' },
                { 'grw', group = 'LSP Workspace Folders' },
                { '<leader>a', group = 'Align' },
                { '<leader>c', group = 'Comment-Box / Context Treesitter / CodeSnap' },
                { '<leader>C', group = 'Colors' },
                { '<leader>D', group = 'Debug' },
                { '<leader>O', group = 'Ollama' },
                { '<leader>Oa', group = 'Avante' },
                { '<leader>d', group = 'Diffview / Debug' },
                { '<leader>ds', group = 'Dap Step' },
                { '<leader>e', group = 'Neo-tree' },
                { '<leader>f', group = 'File' },
                { '<leader>g', group = 'Git' },
                { '<leader>ga', group = 'Align Operators' },
                { '<leader>h', group = 'Hop Motion' },
                { '<leader>l', group = 'LSP/Lazy' },
                { '<leader>m', group = 'Show Messages' },
                { '<leader>n', group = 'Project Notes' },
                { '<leader>o', group = 'Oil File Manager' },
                { '<leader>p', group = 'Image Preview' },
                { '<leader>r', group = 'Search & Replace' },
                { '<leader>R', group = 'Rest API' },
                { '<leader>s', group = 'Flash/Search' },
                { '<leader>t', group = 'ToggleTerm / Todo Comments' },
                { ']t', desc = 'Next todo comment' },
                { '[t', desc = 'Previous todo comment' },
                { '<leader>w', group = 'Save/Toggle' },
                { '<leader>y', group = 'Yanky' },
                { '<leader><leader>', group = 'Smart Splits Swap' },
                { '<space>', group = 'Space Commands' },
                { '<space>b', group = 'Buffer' },
                { '<space>e', group = 'Neo-tree' },
                { '<space>g', group = 'Glance LSP' },
                { '<space>h', group = 'Window Navigation (hjkl)' },
                { '<space>i', group = 'IncRename / Inlay Hints' },
                { '<space>j', group = 'Window Navigation (hjkl)' },
                { '<space>k', group = 'Window Navigation (hjkl)' },
                { '<space>l', group = 'Window Navigation (hjkl)' },
                { '<space>m', group = 'Maximize / Messages' },
                { '<space>n', group = 'Noice' },
                { '<space>o', group = 'Outline' },
                { '<space>v', group = 'Visual/Flash' },
                { '<space>x', group = 'Trouble' },
                { '<space>\\', desc = 'Split Window Vertically' },
                { '<space>/', desc = 'Split Window Horizontally' },
                { 'g', group = 'Go/LSP Functions' },
                { 'z', group = 'Spell/Folds' },
                { '<C-a>', desc = 'Select All' },
                { '<M-UP>', desc = 'Resize Pane Up' },
                { '<M-DOWN>', desc = 'Resize Pane Down' },
                { '<M-LEFT>', desc = 'Resize Pane Left' },
                { '<M-RIGHT>', desc = 'Resize Pane Right' },
                { '<A-h>', desc = 'Smart Resize Left' },
                { '<A-j>', desc = 'Smart Resize Down' },
                { '<A-k>', desc = 'Smart Resize Up' },
                { '<A-l>', desc = 'Smart Resize Right' },
                { '<C-Left>', desc = 'Smart Move Left' },
                { '<C-Down>', desc = 'Smart Move Down' },
                { '<C-Up>', desc = 'Smart Move Up' },
                { '<C-Right>', desc = 'Smart Move Right' },
                { '<C-\\>', desc = 'Smart Move Previous' },
                { '<c-j>', desc = 'Move Line Down' },
                { '<c-k>', desc = 'Move Line Up' },
                { '<S-Left>', desc = 'Buffer Previous' },
                { '<S-Right>', desc = 'Buffer Next' },
                { 's', desc = 'Flash Jump' },
                { '-', desc = 'Snipe Buffer Menu' },
            },
        },
        win = {
            border = 'single',
            no_overlap = false,
            title_pos = 'center',
        },
        sort = { 'manual', 'group', 'lower' },
    },
}
