return {
    'folke/which-key.nvim',
    event = 'VeryLazy',
    enabled = true,
    opts = {
        preset = 'modern',
        expand = 0,
        spec = {
            {
                mode = { 'n', 'v' },
                { '<leader>?', '<cmd>WhichKey<cr>', desc = 'Which-Key Menu' },
                { 'gr', group = 'LSP Functions' },
                { 'grw', group = 'LSP Workspace Folders' },
                { '<leader>c', group = 'Comment-Box / Context Treesitter' },
                { '<leader>O', group = 'Ollama' },
                { '<leader>Oa', group = 'Avante' },
                { '<leader>d', group = 'Diffview / Debug' },
                { '<leader>ds', group = 'Dap Step' },
                { '<leader>f', group = 'File' },
                { '<leader>g', group = 'Git' },
                { '<leader>h', group = 'Hop Motion' },
                { '<leader>l', group = 'Lazy' },
                { '<leader>m', group = 'Show Messages' },
                { '<leader>t', group = 'ToggleTerm / Todo Comments' },
                { '<space>b', group = 'Buffer' },
                { '<space>g', group = 'Glance LSP' },
                { '<space>i', group = 'IncRename / Inlay Hints' },
                { '<space>n', group = 'Noice' },
                { '<space>x', group = 'Trouble' },
            },
        },
        win = {
            border = 'single',
            no_overlap = false,
            title_pos = 'center',
        },
        sort = { 'manual', 'group', 'lower' },
    },
}
